### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by surrutiaquir** [saullocastro/cubature#29]
Thanks a lot for this package!

I think I have installed it correctly on my laptop, but every time I call it I get the following error message:

`Seba-Macbook:cubature-master surrutiaquir$ python prueba.py                                                                                  
Traceback (most recent call last):
  File "/Users/surrutiaquir/Downloads/cubature-master/prueba.py", line 1, in <module>
    from cubature import cubature
  File "/Users/surrutiaquir/Downloads/cubature-master/cubature/__init__.py", line 41, in <module>
    from .cubature import *
  File "/Users/surrutiaquir/Downloads/cubature-master/cubature/cubature.py", line 3, in <module>
    from ._cubature import cubature as _cython_cubature
ModuleNotFoundError: No module named 'cubature._cubature'`

Any ideas? Thank you in advance.

**Comment by surrutiaquir** [comment]
My bad... I just needed to execute first: `sudo python setup.py build_ext --inplace`
It's working now, thanks!

**Comment by saullocastro** [comment]
@surrutiaquir , it forced me to do some updates in the package. Good luck with the project!
